/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Run;

import GetConnect.MyConnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author monki
 */
public class CreateOrder extends javax.swing.JFrame {

    public static Home home;
    public static String employeeCode;
    private String customerID = "";
    private int purchaseID;
    String phone_valid = "0([0-9]{9,11})";
    Pattern p = Pattern.compile(phone_valid);
    Matcher m;

    /**
     * Creates new form CreateOrder
     */
    public CreateOrder() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnReturn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbQuantity3 = new javax.swing.JLabel();
        txtTotalPrice = new javax.swing.JTextField();
        tblOrderMobi = new javax.swing.JScrollPane();
        tbOrderItemList = new javax.swing.JTable();
        btnAddMobi = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnCheckCus = new javax.swing.JButton();
        txtCheckCus = new javax.swing.JTextField();
        lbCusName = new javax.swing.JLabel();
        txtCusName = new javax.swing.JTextField();
        lbCusName1 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        lbCusName2 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        lbCusName3 = new javax.swing.JLabel();
        txtComAddress = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Create Order");
        jLabel1.setToolTipText("");

        btnReturn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/return.png"))); // NOI18N
        btnReturn.setText("Return");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Purchase Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lbQuantity3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbQuantity3.setText("Total Price");
        lbQuantity3.setToolTipText("");

        txtTotalPrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTotalPrice.setText("0");

        tbOrderItemList.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbOrderItemList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MobiID", "Mobile Name", "Quantity", "Unit Price", "Total Unit Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblOrderMobi.setViewportView(tbOrderItemList);
        if (tbOrderItemList.getColumnModel().getColumnCount() > 0) {
            tbOrderItemList.getColumnModel().getColumn(0).setResizable(false);
            tbOrderItemList.getColumnModel().getColumn(1).setResizable(false);
            tbOrderItemList.getColumnModel().getColumn(2).setResizable(false);
            tbOrderItemList.getColumnModel().getColumn(3).setResizable(false);
            tbOrderItemList.getColumnModel().getColumn(4).setResizable(false);
        }

        btnAddMobi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAddMobi.setText("Add Mobile");
        btnAddMobi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMobiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbQuantity3)
                .addGap(102, 102, 102)
                .addComponent(txtTotalPrice)
                .addContainerGap())
            .addComponent(tblOrderMobi, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(btnAddMobi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddMobi)
                .addGap(18, 18, 18)
                .addComponent(tblOrderMobi, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbQuantity3)))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14)))); // NOI18N

        btnCheckCus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCheckCus.setText("Check Customer");
        btnCheckCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckCusActionPerformed(evt);
            }
        });

        txtCheckCus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lbCusName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbCusName.setText("Customer Name");
        lbCusName.setToolTipText("");

        txtCusName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbCusName1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbCusName1.setText("Phone Number");
        lbCusName1.setToolTipText("");

        txtPhone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbCusName2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbCusName2.setText("Address");
        lbCusName2.setToolTipText("");

        txtAddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbCusName3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbCusName3.setText("Company Address");
        lbCusName3.setToolTipText("");

        txtComAddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnCheckCus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCheckCus, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbCusName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCusName, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(lbCusName1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbCusName2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(lbCusName3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtComAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCheckCus)
                    .addComponent(txtCheckCus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCusName)
                    .addComponent(txtCusName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCusName1)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCusName2)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCusName3)
                    .addComponent(txtComAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButton1.setText("Create Order");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(143, 143, 143))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(117, 117, 117)
                        .addComponent(btnReturn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReturn)
                    .addComponent(jButton1))
                .addGap(6, 6, 6))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddMobiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMobiActionPerformed
        AddMobileToOrder amto = new AddMobileToOrder();
        amto.setVisible(true);
    }//GEN-LAST:event_btnAddMobiActionPerformed

    private void btnCheckCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckCusActionPerformed
        String searchByPhone = txtCheckCus.getText();
        try {
            Connection conn = MyConnect.getConnection();
            PreparedStatement ps = conn.prepareStatement("select * from Customer where PhoneNumber = ?");
            ps.setString(1, searchByPhone);
            //PreparedStatement ps = conn.prepareStatement("select * from Employee"); 
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                String id = rs.getString("CustomerID");
                String customerName = rs.getString("CustomerName");
                String phoneNumber = rs.getString("PhoneNumber");
                String customerAddress = rs.getString("CustomerAddress");
                String customerCompanyAddress = rs.getString("CustomerCompanyAddress");
                customerID = id;
                txtCusName.setText(customerName);
                txtCusName.setEditable(false);
                txtPhone.setText(phoneNumber);
                txtPhone.setEditable(false);
                txtAddress.setText(customerAddress);
                txtAddress.setEditable(false);
                txtComAddress.setText(customerCompanyAddress);
                txtComAddress.setEditable(false);
            } else {
                JOptionPane.showMessageDialog(null, "New customer. Please enter information.");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnCheckCusActionPerformed
    public String getNewCustomerID() {
        try {
            Connection conn = MyConnect.getConnection();
            PreparedStatement ps = conn.prepareStatement("select MAX(CustomerID) as CustomerID from Customer");
            ResultSet rs = ps.executeQuery();
            rs.next();
            return rs.getString("CustomerID");
        } catch (Exception e) {
            e.printStackTrace();
        }
        return "";
    }

    public void insertPurchase() {
        int totalPrice = Integer.valueOf(txtTotalPrice.getText());
        try {
            Connection conn = MyConnect.getConnection();
            PreparedStatement ps = conn.prepareStatement("insert into Purchase values(?, ?, ?, ?) ");
            DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
            Date date = new Date();
            ps.setString(1, customerID);
            ps.setString(2, employeeCode);
            ps.setString(3, dateFormat.format(date));
            ps.setInt(4, totalPrice);
            ps.executeUpdate();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    public int getPurchaseID() {
        try {
            Connection conn = MyConnect.getConnection();
            PreparedStatement ps = conn.prepareStatement("select MAX(purchaseID) as purchaseID from Purchase");
            ResultSet rs = ps.executeQuery();
            rs.next();
            return rs.getInt("purchaseID");
        } catch (Exception e) {
            e.printStackTrace();
        }
        return 0;
    }

    public void insertPurchaseDetail() {
        try {
            Connection conn = MyConnect.getConnection();
            DefaultTableModel model = (DefaultTableModel) tbOrderItemList.getModel();
            int numberOfRows = model.getRowCount();
            for (int row = 0; row < numberOfRows; row++) {
                int mobiID = Integer.valueOf(model.getValueAt(row, 0).toString());
                int quantity = Integer.valueOf(model.getValueAt(row, 2).toString());
                int unitPrice = Integer.valueOf(model.getValueAt(row, 3).toString());
                int totalUnitPrice = Integer.valueOf(model.getValueAt(row, 4).toString());
                PreparedStatement ps = conn.prepareStatement("insert into PurchaseDetail values(?,?, ?, ?, ?) ");
                ps.setInt(1, purchaseID);
                ps.setInt(2, mobiID);
                ps.setInt(3, quantity);
                ps.setInt(4, unitPrice);
                ps.setInt(5, totalUnitPrice);
                ps.executeUpdate();
            }
            JOptionPane.showMessageDialog(null, "Order created successfully");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (customerID.equals("")) {
            String txtCustomerName = txtCusName.getText();
            String txtCusPhone = txtPhone.getText();
            String txtCusAddress = txtAddress.getText();
            String txtCompAddress = txtComAddress.getText();
            m = p.matcher(txtCusPhone);

            try {
                if (!m.matches()) {
                    JOptionPane.showMessageDialog(null, "Invalid phone number!");
                    txtPhone.setText("");
                } else {
                    Connection conn = MyConnect.getConnection();
                    PreparedStatement ps = conn.prepareStatement("INSERT INTO Customer VALUES(?,?,?,?)");
                    ps.setString(1, txtCustomerName);
                    ps.setString(2, txtCusPhone);
                    ps.setString(3, txtCusAddress);
                    ps.setString(4, txtCompAddress);
                    ps.executeUpdate();

                    customerID = getNewCustomerID();

                    insertPurchase();

                    purchaseID = getPurchaseID();

                    insertPurchaseDetail();

                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            insertPurchase();
            purchaseID = getPurchaseID();
            insertPurchaseDetail();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMobi;
    private javax.swing.JButton btnCheckCus;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbCusName;
    private javax.swing.JLabel lbCusName1;
    private javax.swing.JLabel lbCusName2;
    private javax.swing.JLabel lbCusName3;
    private javax.swing.JLabel lbQuantity3;
    public static javax.swing.JTable tbOrderItemList;
    private javax.swing.JScrollPane tblOrderMobi;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCheckCus;
    private javax.swing.JTextField txtComAddress;
    private javax.swing.JTextField txtCusName;
    private javax.swing.JTextField txtPhone;
    public static javax.swing.JTextField txtTotalPrice;
    // End of variables declaration//GEN-END:variables
}
